---
title: "Stability Regression App README"
author: "Rachel Molloy"
date: "7/4/2021"
output: html_document
---

# **Regression for Stability**
This app is used for Stability studies to dynamically conduct a regression analysis and predict the shelf-life of BDB Research Reagents. There are two workflows this app will support: the Manual and the OMIQ Workflow.

*Manual Workflow*: The experimental data was gated/analyzed manually using FlowJo (the stats generated from FlowJo must be copied into the template and uploaded to the App, although the template is structured very similarly to what the team is currently using).

*OMIQ Workflow*: The experimental data was gated/analyzed using the OMIQ pipeline. An initial regression analysis and shelf-life prediction was already conducted during the execution of OMIQ, but changes may be necessary to the analysis. Therefore, the team may need to use the App to do a dynamic data review, in which case they would upload their OMIQ reports and the `all_stats.csv` file from OMIQ. 

The only differences between the Manual Workflow and OMIQ Workflow in terms of Stability Regression App usage are the sidebar panel layout and user inputs/uploads, and the downloadable output formats.


***

## Sidebar Panel Overview

The sidebar panel using multiple renderUIs based on the `input$analysis_type`:

```r
uiOutput('manual_or_omiq')
```
This renders the 2 `downloadButton`s for the Stats Template and Example if the Manual analysis option is selected, and the `fileInput` for the stats file to be uploaded. 

```r
uiOutput('manual_or_omiq_cell_pop')
```
This renders the Marker Name text outputted to the sidebar panel, as well as a `selectInput` option to select the cell population to analyze, if `input$analysis_type == "OMIQ"`. The list of cell populations to analyze is based on a list of unique cell populations found in the "pop" column of the `all_stats.csv` file. If the Manual analysis option is selected, nothing additional outputs to the UI.

Several user input parameters used to establish the model and criteria for selecting shelf-life are shown on the sidebar panel for both analysis types:
```r
radioButtons('polynomial_order', "Order of Polynomial", ..., selected = "Linear", ...) # select model polynomial order
selectInput('CI', 'Confidence Interval', ..., selected = 0.95) # select confidence interval to use and find shelf-life from
textInput('threshold', '% of 4C Reference MFI Threshold', value=75) # MFI Threshold to find shelf-life from
```
The defaults selected are default values used in the OMIQ regression report scripts, and have been established by the team as criteria to use for finding shelf-life. If a user selects a different option for any of these parameters, the results will be updated and reflected in the UI and all downloadable outputs. However, the selected parameters themselves will not be outputted to any of the downloadable outputs, so users must indicate so in the Notes section.

If a user selects a polynomial order and the highest order coefficient p-value > 0.05, a warning will output to the UI to indicate to the user that there is no statistical significance in the model order selected:

```r
uiOutput('warning_ui_polynomial_choice')
```

Once a stats file has been successfully uploaded to the app, all unique concentration values will be read from the stats file input and the list of concentrations will be outputted to a `checkboxGroupInput` on the sidebar panel:

```r
uiOutput('concentration_checkGroupInput')
```
This provides the user with the option to exclude entire titration values from the regression analysis and shelf-life prediction. The concentration choice names and values are configured by calling the following functions:

```r
concentration_choice_names <- reactive({ concentration_choiceNames(raw_upload_data()) })
concentration_choice_values <- reactive({ concentration_choiceValues(concentration_choice_names()) })
```
where the `concentration_choiceNames(...)` function finds the list of unique concentrations listed in the stats file upload and appends the values with "ng/test" (this means that the units provided in this App will always be in "ng/test", so the user must upload the data with concentrations in "ng/test"), and the `concentration_choiceValues(...)` function assigns each concentration to a value. All selected concentrations will be assigned to `input$concentrations_to_include`. More details on this are provided in the "How Excluded Data is Handled" section of the README file.

The final `renderUI` on the sidebar panel lays out the UI for configuring final downloadable output, depending on the analysis type selected:
```r
uiOutput('downloadable_outputs_ui')
```

If `input$analysis_type == "Manual"`, the ouput will include the option to add text to the top right corner of certain slides in the PPT output, and adjust the prefixes of the title of certain slides, based on which cell population the stats reflect (the typical Manual Workflow for the Stability team is that if more than 1 cell population is present and analyzed, the slides will represent the cell population name by the 'P1', 'P2', etc. prefix and the free text in the top right corner of the slides). The user can then add a name to the final PPT output and download the PPT with the `input$pptx_id` download button.

If `input$analysis_type == "OMIQ"`, the output will include options to:

1. Download the new regression report generated from any analysis done on the App for an individual cell population (`input$regression_report`)
2. Upload the individual regression report downloaded from `input$regression_reports_indiv`
3. Upload the initial stability report generated by OMIQ that includes the full stability analysis and regression report for all cell populations (`input$omiq_report_upload`)
4. Download the final regression report (`input$regression_report_bundled`) that bundles the individual regression report created by the App with the final OMIQ stability report uploaded from step 3

***

## Main Panel Overview

### Stats Table tab
The % of 4C Reference MFI Table is rendered from:
```r
DT::dataTableOutput("reference_mfi_data_table_keep_only")
```
where the data populated is from the reactive expression generated using the `create_reference_MFI_table_wide_with_keeps(...)` function, which takes in only the data included by the user as an argument. 
```r
reference_MFI_data_to_include_from_keep <- reactive({
    create_reference_MFI_table_wide_with_keeps(keep())
})
```
All concentrations excluded from the sidebar panel will not be shown here, and all excluded individual data points will be NULL in the table.

***

### Plots tab
All plots typically generated by the Stability team are outputted to this tab for the *raw* data only. Data points excluded in the GUI will not be excluded in any of these plots. 

```r
plotOutput('mfi_vs_concentration') # uses mfi_vs_concentration_plot(...) function
plotOutput('mfi_vs_time') # uses mfi_vs_time_plot(...) function
plotOutput('stain_index') # uses stain_index(...) function
plotOutput('signal_to_noise') # uses signal_to_noise(...) function
plotOutput('percent_positive') # uses percent_positive(...) function
plotOutput('percent_of_4C_MFI') # uses percent_of_4C_MFI(...) function
```
Note that the Stain Index and Signal-to-Noise calculations are executed inside their respective functions (see each function referenced in the commented code above). If the Stain Index is Inf or if the rSD- statistic is NA, the Stain Index will be set to NA.

***

### Regression & Shelf-Life tab 

The regression plot plots the % of 4C Reference MFI vs Time for all concentrations selected by the user. The `plotOutput` render function includes additional parameters:
a) `click` to select and toggle off/on individual data points
b) `dblclick` to zoom in and out of the plot
c) `brush` to create a rectangle around the area to zoom in and out of on the plot

```r
plotOutput("regression_plot_output", height = 350,
           click = "regression_plot_output_click",
           dblclick = "regression_plot_zoom_dblclick",
           brush = brushOpts(
               id = "regression_plot_output_brush",
               resetOnNew = TRUE
           )
)
```
The zoom functionality is configured using the `add_zoom(...)` function inside the `server` function.

```r
plot_range <- add_zoom("regression_plot_output")
```

Individual data points that are excluded will be set to `FALSE` in the `vals$keeprows` array, and data points included will be kept as `TRUE` in the array, and used in the analysis. All data points that were excluded on the plot can be reset to be included in the regression analysis and the plot by clicking `input$exclude_reset`. Any concentrations excluded from the sidebar panel will not be reset with this function.

The plot itself is generated using the following function (with `keep()` being the data argument):
```r
regression_plot_global(...) <- function{}
```
and then by applying several other parameters to the plot that are specific to the functionality of the UI, include `geom_point()` for the `exclude()` data, which has no fill and a black outline, the regression fit equation and R^2 value, and the plot range, which needs to be reactive since the user can zoom in on sections of the plot. The `regression_plot_global(...)` function is used to generate both the plots on the UI and plots in the downloadable outputs, and takes arguments related to the font sizes and data point sizes, which differ between the output methods. 

The shelf-life prediction is based on the lower confidence bound, where the confidence interval is set by the user input `input$CI`. The lower shelf life is assigned the variable:
```r
lower_shelf_life <- reactive({ solve_for_lower_shelf_life(...) })
```
and outputted to the UI as:
```r
uiOutput('check_lower_shelf_life')
```
The shelf life from the lower bound is determined using the function `solve_for_lower_shelf_life(...)`. Arguments include the shelf-life/model parameters configured by the user, including the `input$CI`, `input$polynomial_order` and `input$threshold` (% of 4C Reference MFI Threshold), as well as the data frame with the included data points only. This function uses the `predict()` built-in R function to find the equation of the confidence interval. The `uniroot()` function is then used to find the intersection between the lower confidence bound and the % of 4C Reference MFI Threshold (`input$threshold`). If the lower confidence bound never intersects the `y = input$threshold` equation, `NULL` will be returned as the shelf-life, and a warning will be outputted to the user on the UI, configured in the `uiOutput('check_lower_shelf_life)`. If an intersection is found, the resulting shelf-life will be rounded to 2 decimal places and outputted (in years). 

The "SAP" shelf-life prediction is also outputted to the UI:

```r
uiOutput('check_rounded_shelf_life')
```
This is the shelf-life prediction from the lower confidence bound with the SAP rounding rule set applied. 

```r
rounded_shelf_life(lower_shelf_life())
```
The rounding rules are configured in the `rounded_shelf_life(...)` function, and will round the `lower_shelf_life()` prediction down to the nearest half integer. If the shelf-life prediction is above 5 years, it will round down to 5 years to avoid extrapolation. If the shelf-life is less than or equal to 1.5 years, the minimum shelf-life required by most BDB Research Reagents, it will not round but output the actual shelf-life.

For both the raw shelf-life and SAP shelf-life, the output will be in years and then converted to days using the conversion constants established by the team, `RAW_SL_TO_DAYS` and `SAP_SL_TO_DAYS`.

A statistical technique called the Polynomial Evaluation of Linearity is conducted to determine the statistical significance of the model, particularly the polynomial order selected. The `get_model_coeff_pvalues(...)` function finds the p-values of all coefficients in the model equation, using the `lm()` and `summary()` built-in R functions.

```r
poly_eval <- reactive({ 
    req(raw_upload_data())
    get_model_coeff_pvalues(keep(), poly_order()) 
})
```
The model p-value, determined in the reactive expression `model_p_value()`, is based on the polynomial order selected by the user on the UI. If the p-value is >= 0.05, the model coefficient is not statistically significant, and a warning will be outputted to the user on the UI:

```r
uiOutput('model_coeff_pvalue')
```

Other warnings outputted to the UI include:
```r
uiOutput('warning_ui_rsq') # warns user if R^2 value < 0.80
uiOutput('warning_ui_slope') # warns user if slope of regression fit (not confidence bound) is positive
```
to warn the user if the R^2 value is below 0.80 or if the slope of the regression fit line (not the confidence bound line) is positive.

Finally, a user can add notes relevant to their experiment or data review, and will be passed to the downloadable outputs:

```r
textAreaInput("notes", "Notes", ...)
```

### Residuals & Normality Checks tab 

This tab is used as a quality assessment, where the residuals and the normality of the residuals are calculated and visualized. The residuals are calculated using the `global.R` function `find_residuals(...)`.

The Residual vs Fit Plot is created using the `residual_vs_fit_plot(...)` function. The tooltip is added using the `residual_vs_fit_plot_w_tooltip(...)` function to indicate which time point and concentration each data point references. The latter function is only used in the UI. The plots generated for the downloadable reports reference the `residual_vs_fit_plot(...)` function. This plot be used for the user to identify outliers or patterns in the residuals, which would indicate bias. 

```r
plotlyOutput('residual_fit_plot')
```
A Histogram of Residuals plot is generated using the `residual_histogram(...)` function, and is used to visualize distribution of the residuals.

```r
plotlyOutput('residual_histogram')
```
A Normal Probability of Residuals plot is generated to visualize whether there is normal distribution in the residuals, and can also be used to identify outliers. The plot is generated using the `normal_probability_plot(...)` function. An additional function, `normal_probability_plot_w_tooltip(...)`, is used to output the plot to the UI only with a tooltip using the `plotly` library. Plots in the downloadable outputs reference the `normal_probability_plot(...)` function only. 

```r
plotlyOutput('normal_prob_plot_output')
```
An Anderson-Darling Normality Test is also conducted using the function `anderson_darling_normality_test(...)`, where the p-value is returned. If the p-value is less than 0.05, normal distribution is not statistically significant, and a warning will be outputted to the user on the UI indicating so. 

```r
uiOutput('anderson_darling_pvalue_output')
```

***

## How Uploaded Stats File is Handled

Data is uploaded on the Sidebar Panel. Both the Manual and OMIQ analysis types use the same `fileInput` id,

```r
fileInput("raw_upload","Choose stats file to upload",...)
```
but accept different file types (Manual accepts .xlsx files, OMIQ accepts .csv files since that is the file type to which OMIQ outputs the stats). 

The first step is convert the stats data into a consistent format to be used for the analysis:

```r
raw_upload_data_prelim()
```
This reactive expression reads in the `input$raw_upload` data, and if the analysis type selected was OMIQ, an additional step is taken to add a sample/control column using the function `add_sample_or_control_column(...)` function to indicate which stats refer to the sample and which refer to the control (and are therefore redundant). This reactive function also includes a `validate()` statement to check that the file extension is as expected, given the `input$analysis_type` selected. If the file extension is incorrect, help text will be outputted to the UI. 

Next, if the OMIQ analysis type is selected, a `selectInput` will be outputted to the sidebar panel where the user can select the cell population they would like to analyze. The `configure_stats(...)` function from the `regression_report.R` file will be called to return the stats in the expected format from only the selected cell population. The reactive expression that returns the stats in the final, expected format is:

```r
raw_upload_data()
```
The % of 4C Reference MFI stats are then calculated using the function
```r
calculate_perct_4C_MFI(...) <- function{}
```
and a data frame of the raw stats, plus a new column with the % of 4C Reference MFI stats, is returned to the reactive expression `raw_upload_data_with_perct_MFI()`.


***

## How Excluded Data is Handled

### Concentrations Excluded:
In the reactive expression,
```r
concentrations_to_include_list()
```
the selected concentrations to include in the analysis will be used as an argument to the function:

```r
concentrations_to_keep(...) <- function{}
```
This will output a data frame with data that includes only the concentrations the user wishes to include in the analysis, and is assigned to the reactive expression:

```r
reference_MFI_data_to_include()
```
This is used as an argument to the function:
```r
melt_reference_mfi_table(...) <- function{}
```
This function uses the `melt()` function to transform the data frame so % of 4C Reference MFI values are all listed in the column "value", and all concentrations are listed in the column "Concentrations". 

***

### Individual Data Points Excluded:

The outputted data frame returned by the `melt_reference_mfi_table(...)` function is `selected_melted_data()`, and this is used several times throughout the `server` function as an argument/parameter for the `keep()` and `exclude()` reactive expressions, which are two separate data frames with the included and excluded data points only. A `reactiveValues()` called `vals` is initialized, and once the `input$raw_upload` stats file is uploaded, `vals$keeprows` will be updated and only the included data points, given by `selected_melted_data()`, will be set to `TRUE`. 

```r
# For storing which rows have been excluded
vals <- reactiveValues(
    keeprows = rep(TRUE, 56)
)
# Update values of included rows whenever new data is uploaded
observeEvent(input$raw_upload, {
    vals$keeprows <- rep(TRUE, nrow(selected_melted_data()))
    
# Two separate dataframes with the included and excluded data points only, respectively.
keep    <- reactive({ selected_melted_data()[ vals$keeprows, , drop = FALSE] })
exclude <- reactive({ selected_melted_data()[!vals$keeprows, , drop = FALSE] })
})
```

When a user clicks an individual data point on the regression plot, the `vals$keeprows` array is updated to `FALSE`.
```r
# Toggle points that are clicked
observeEvent(input$regression_plot_output_click, {
    res <- nearPoints(selected_melted_data(), input$regression_plot_output_click, allRows = TRUE) 
    vals$keeprows <- xor(vals$keeprows, res$selected_) # keeprows array is updated 
})
```   
Any final data the user decides to include in the analysis is assigned in the data frame `keep()` and is used as an argument to the plots, tables and calculations for the final outputs. 
    


This will output the % of 4C Reference MFI dataframe that is rendered to the first tab of the main panel in the UI, "Stats Table", with only the concentrations to include in the analysis outputted. The output of this function is:
***

## Final Outputs / Downloads

### Manual Workflow - PPT Output
If `input$analysis_type == 'Manual'`, the final output downloaded with the `output$pptx_id <- downloadHandler()` is in a PowerPoint presentation format, and uses the `library(officer)` package to configure. 

The presentation uses the `bd_template_homemade.pptx` PPT template and the slides are formatted as follows:
1) Protocol
2) SSC Plots
3) Histogram Plots
4) MFI Plots
5) Concentration vs Time #1
6) Concentration vs Time #2
7) Regression Analysis + Shelf-Life
8) Residuals #1
9) Residuals #2 - Normality

Slides 1-3 will be blank other than a title and the model system text for slide #3, and the user will need to copy-paste their plots/protocol into these slides manually after downloading.

Slides 4-6 include the same plots generated on the 'Plots' tab. 

Slides 7-9 include the plots and tables of data generated from the 'Regression & Shelf-Life' tab and 'Residuals & Normality' tab. These slides are generated twice, one with the raw data only (to preserve all stats, no exclusions), and one with only the data included by the user from the UI. The latter references the same reactive expressions used everywhere in the UI. The former references new reactive expressions with the prefix `raw_` with the argument `raw_melted_data()`:
```r
raw_melted_data <- reactive({ na.omit(melt_reference_mfi_table(raw_reference_MFI_data_wide())) })
```
If no data was excluded, the PPT will output a copy of slides 7-9 and the user will have to manually delete them after downloading the PPT. Whether data was excluded or not, the 2nd set of the Regression Analysis + Shelf-Life slide will have a notes textbox with any notes the user added in the `input$notes` textbox from the UI. 

The `raw_shelf_life_summary_flextable()` and `modified_shelf_life_summary_flextable()` are tables using the `library(flextable)` that include the shelf-life predictions, model p-value, and R^2 values. The `raw_anderson_darling_flextable()` and `modified_anderson_darling_flextable()` are tables using the same library that output the anderson-darling p-value. The color flags are configured with `raw_model_pvalue_color()`, `modified_model_pvalue_color()`, `raw_ad_pvalue_color()`, and `modified_ad_pvalue_color()` reactive expressions. 

***

### OMIQ Workflow - PDF Output

If the OMIQ analysis type is selected, the final output users will download will be a PDF, generated by the following function:
```r
build_regression_report_gui_modified(...) <- function{}
```
This function generates the 3 page regression analysis report for an individual cell population analysis, including a title page. 

First, the % of 4C MFI table is generated with the following function:
```r
df <- get_stats_table_for_mfi_table(stats_file, cell_pop, df_melt)
```
This calls many of the same functions from the `global.R` file that are used in the `server.R` script for the analysis executed in the App. 

Inside the `build_regression_report_gui_modified(...)` function, pngs of the tables are generated with the following functions:

```r
reference_mfi_table_png <- perc_4C_mfi_table_png(...) # table with % of 4C Reference MFI data
shelf_life_summary_png <- shelf_life_estimates_table_png(...) # table of shelf-life predictions
normality_pvalue_png <- anderson_darling_p_value_png(normality_p_value) # table with anderson-darling p-value

```
The following two functions then take the plots and table pngs and `print()` them to a pdf page:

```r
regression_pdf <- function{} # page with refression plots and shelf-life tables
quality_checks_pdf <- function{} # page with residual and normality plots/table
```
Finally, a title page will be generated and added to the beginning of the individual regression analysis report:

```r
title_page = regression_gui_title_page(...)
```
The outputted regression analysis report for a given cell population will be written to the following reactive expression:
```r
create_regression_report_modified()
```
This reactive expression returns the report, which will be downloaded when the `input$regression_report` download button is clicked to download the individual regression analysis report generated from the UI. The user must then upload any individual regression analysis reports generated by the App to the `input$regression_reports_indiv` file input handler, along with the OMIQ stability report generated from the OMIQ pipeline. Once both sets of files are uploaded, the user can then click the `input$regression_report_bundled` download button to download the final regression report, named `regression_report_output_bundled.pdf`, which is generated by calling the following function from `regression_report.R` script:

```r
merged_pdfs_for_gui(input$omiq_report_upload$datapath, input$regression_reports_indiv$datapath, input$plate_id)
```
This merges the report generated from OMIQ with the individual regression reports generated using the App (the individual reports from the App each have their own title page and are all added to the end of the main OMIQ Stability report). This is saved to the `docker_regression_directory` path inside the folder named after the `input$plate_id` with the filename `final_regression_report_post_review.pdf`.

Most of the code to generate the pdf regression report for the OMIQ workflow can be found in the `regression_report.R` script. 



